name: test-workflow
on: [push]
jobs: 
  explore-test-workflow: 
     runs-on: ubuntu-latest
     steps:
     - run: echo " This is a test "
     - run: echo " Triggered by ${{ github.event_name }} event "
     - run: echo " The job is running on a ${{ runner.os}} server hosted by GITHub "
     - run: echo " The name of branch and Repo ${{github.ref}} and ${{github.repository}}"
     - name: List files in the repository 
       run: |
          ls ${{ github.workspace }}
     - run: echo "Status of the Job is ${{ job.status}}"
  Second-Job:
      name: The second job running on a second runner
      runs-on: ubuntu-latest
      needs: explore-test-workflow
      steps:
      - run: echo " Triggered by ${{ github.event_name }} event "
   
