name: test-workflow
on: [push]
jobs: 
   explore-test-workflow: 
     runs-on: ubuntu-latest
     steps:
     - run: echo " This is a test "
     - run: echo " Triggered by ${{ github.event_name }} event "
     
        
